require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 2.7

RSpec/MultipleExpectations: # expectが多すぎて警告される対処
  Max: 20

RSpec/ExampleLength: # 行数が多すぎて警告される対処
  Max: 20
